### ISSUE TITLE
I am not able to update the widget at every midnight. Can you please explain how can I update widget at midnight daily?

### ISSUE THREAD

**Issue by jinia-konar** [rafid059/bangla-date-widget#1]

**Comment by rafid059** [comment]
This is VERY old code. I doubt it still works. Some of the APIs for widgets and alarm manager may have changed over the years. You'll have to read up on the documentation. Try updating the widget every 30s or 1min. If that works, then simply increase the interval. Here are some discussions that might be helpful https://stackoverflow.com/questions/27422007/update-android-widget-at-midnight

**Comment by jinia-konar** [comment]
okay thank you
